### ISSUE TITLE
make numpy-iOS won't build

### ISSUE THREAD

**Issue by dalcacer** [OtoJig/Python-Apple-support#10]
```
xcrun --sdk iphoneos clang -arch arm64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -bundle -undefined dynamic_lookup -fembed-bitcode build/temp.iphoneos.arm64-3.6/numpy/core/src/dummymodule.o -Lbuild/temp.iphoneos.arm64-3.6 -o build/lib.iphoneos.arm64-3.6/numpy/core/_dummy.cpython-36m-darwin.so
exec_command(['xcrun', '--sdk', 'iphoneos', 'clang', '-arch', 'arm64', '--sysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk', '-bundle', '-undefined', 'dynamic_lookup', '-fembed-bitcode', 'build/temp.iphoneos.arm64-3.6/numpy/core/src/dummymodule.o', '-Lbuild/temp.iphoneos.arm64-3.6', '-o', 'build/lib.iphoneos.arm64-3.6/numpy/core/_dummy.cpython-36m-darwin.so'],)
Retaining cwd: /Users/dalcacer/repositories/github.com/@otojig/python_apple_support/build/iOS/packages/numpy
_preserve_environment([])
_update_environment(...)
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
_update_environment(...)
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Command "xcrun --sdk iphoneos clang -arch arm64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -bundle -undefined dynamic_lookup -fembed-bitcode build/temp.iphoneos.arm64-3.6/numpy/core/src/dummymodule.o -Lbuild/temp.iphoneos.arm64-3.6 -o build/lib.iphoneos.arm64-3.6/numpy/core/_dummy.cpython-36m-darwin.so" failed with exit status 1
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10a9efef0>>
Traceback (most recent call last):
  File "/Users/dalcacer/repositories/github.com/@otojig/python_apple_support/build/macOS/python/lib/python3.6/subprocess.py", line 770, in __del__
  File "/Users/dalcacer/repositories/github.com/@otojig/python_apple_support/build/macOS/python/lib/python3.6/subprocess.py", line 1378, in _internal_poll
AttributeError: 'NoneType' object has no attribute 'waitpid'
make: *** [build/iOS/packages/numpy/build/temp.iphoneos.arm64-3.6/libpymath.a] Error 1
```

**Comment by dalcacer** [comment]
Solved via 85c8e4a7ba5b3bc6d78dbd01a5dbe26ee48e0f05
